In [51]:
import numpy as np
from numpy import linalg as LA

4.4
3,4,6,18

In [109]:
def jukes_cantor(alpha,ran,M=None):
    a=alpha
    b=a/3
    if M is None:
        M = np.array([[1-a,b,b,b],[b,1-a,b,b],[b,b,1-a,b],[b,b,b,1-a]])
    p = np.array([[0.2,0.6,0.1,0.1]])
    p = np.resize(p,(4,1))
    P = p
    for i in range(1,1000):
        p = np.matmul(M,p)
        P = np.hstack((P,p))
        eq = np.array([0.25,0.25,0.25,0.25])
        eq = np.resize(eq,(4,1))
        if ran is not None:
            if (p-eq <= ran).all():
                break
#     print(P.shape)
    print(np.transpose(P)[-1:])
    return i

In [110]:
print(jukes_cantor(0.03,0.05))
#27 time steps for value within 0.05 of eq
print(jukes_cantor(0.03,0.01))
#67 time steps for values within 0.01 of eq

print(jukes_cantor(0.06,0.01)) 
#33 time steps for alpha within 0.01 of eq

[[ 0.24295324  0.29932729  0.22885973  0.22885973]]
48
[[ 0.2486233   0.25963688  0.24586991  0.24586991]]
88
[[ 0.24861373  0.25970386  0.2458412   0.2458412 ]]
43


implies eq fastest for alpha=0.06 implies higher probability of mutation
$$Yes, it does hold for other choices

In [103]:
M = np.array([[ 0.82,  0.06,  0.06,  0.06],
 [ 0.06 , 0.82,  0.06,  0.06],
 [ 0.06,  0.06,  0.82,  0.06],
 [ 0.06 , 0.06 , 0.06,  0.82]])
jukes_cantor(0.18,0.01,M)

[[ 0.24678556  0.25321444  0.25964333  0.24035667]]


10

In [104]:
values, vectors = LA.eig(M)

In [105]:
values,vectors

(array([ 0.76,  1.  ,  0.76,  0.76]),
 array([[-0.8660254 ,  0.5       ,  0.46157715, -0.52364833],
        [ 0.28867513,  0.5       ,  0.41762315, -0.31818363],
        [ 0.28867513,  0.5       , -0.77578526,  0.05334892],
        [ 0.28867513,  0.5       , -0.10341504,  0.78848304]]))

In [106]:
M2 = np.array([[0.7,0.1,0.1,0.1],[0.1,0.7,0.1,0.1],[0.1,0.1,0.7,0.1],[0.1,0.1,0.1,0.7]])
jukes_cantor(alpha=0.3,ran=0.005,M = M2)

[[ 0.24860032  0.25139968  0.25419904  0.24580096]]


7

In [108]:
np.matmul(M,M2) #Here alpha3 0.408 ; a1 = 0.18, a2 = 0.3; a3 = a1+a2+4/3(a1*a2)

array([[ 0.592,  0.136,  0.136,  0.136],
       [ 0.136,  0.592,  0.136,  0.136],
       [ 0.136,  0.136,  0.592,  0.136],
       [ 0.136,  0.136,  0.136,  0.592]])